[package]
name = "webview"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
block2.workspace = true
objc2.workspace = true
objc2-app-kit = { workspace = true, features = ["NSWindow", "NSView", "NSGraphics", "NSScreen"] }
objc2-foundation = { workspace = true, features = [
  "NSArray",
  "NSDate",
  "NSEnumerator",
  "NSGeometry",
  "NSHTTPCookie",
  "NSString",
  "NSURL",
  "NSURLRequest",
  "objc2-core-foundation",
] }
objc2-web-kit.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
dirs.workspace = true
webview2-com.workspace = true
windows.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
